name: emberijoginyilatkozatosappproject
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  hexcolor: ^3.0.1
  syncfusion_flutter_calendar: ^20.1.57
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  provider: ^6.0.2
  animated_splash_screen: ^1.2.0
  email_validator: ^2.0.1
  flutter_pw_validator: ^1.4.2
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  animated_text_kit: ^4.2.1
  percent_indicator: ^4.0.0
  connectivity_plus: ^3.0.2
  cloud_firestore: ^4.0.2
  firebase_crashlytics: ^3.0.2
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/
